# -*- coding: utf-8 -*-
"""Bobo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MIEc_Jh1wZVJcvqKp5AG_aMpwBJI9Xe
"""

1+1

a=2

b=3

a+b

c=a+b

c

